#!/usr/bin/env python3
"""summary: plot_b0_amr_overlay.py の処理内容をまとめたスクリプト

plot_b0_amr_overlay.py

Overlay multiple B0 sweep CSVs to visualize the effect of *wall AMR*
(refine factor / threshold) on the HOME-vs-Legacy gap and Hybrid(B0)
error reduction.

Typical workflow:
 1) Run sweeps:
 powershell -ExecutionPolicy Bypass -File scripts\run_b0_sweeps.ps1 -Exe .\build\Release\fluidsim_compare.exe

 2) Overlay for a shape (teardrop/fan):
 python scripts/plot_b0_amr_overlay.py results_b0 teardrop out_teardrop_overlay.png

Notes:
- The script looks for files named like:
 b0_teardrop_amr2_thr0p5.csv
 (generated by run_b0_sweeps.ps1)
- It auto-groups by (amr_factor, amr_threshold)."""

import sys
import csv
import re
from pathlib import Path
import matplotlib.pyplot as plt


def read_csv(path: Path):
    """summary: 入力を読み取る
param path: 入力パラメータ
return: 戻り値"""
    rows = []
    with path.open("r", encoding="utf-8", errors="ignore") as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    header_idx = None
    for i, ln in enumerate(lines):
        if ln.startswith("d0,"):
            header_idx = i
            break
    if header_idx is None:
        raise RuntimeError(f"CSV header not found in {path}")
    reader = csv.DictReader(lines[header_idx:])
    for r in reader:
        rows.append(r)
    return rows


def to_float(x: str) -> float:
    """summary: to_float の処理を行う
param x: 入力パラメータ
return: 戻り値"""
    try:
        return float(x)
    except Exception:
        return float("nan")


def main():
    """summary: スクリプトのエントリポイントを実行する
param: なし
return: 戻り値"""
    if len(sys.argv) < 4:
        print("Usage: python scripts/plot_b0_amr_overlay.py <results_dir> <shape_tag> <out.png>")
        print("  shape_tag: teardrop | fan")
        sys.exit(1)

    results_dir = Path(sys.argv[1])
    shape_tag = sys.argv[2]
    out_path = Path(sys.argv[3])

    # Match the naming from run_b0_sweeps.ps1
    # Example: b0_teardrop_amr2_thr0p5.csv
    pat = re.compile(rf"^b0_{re.escape(shape_tag)}_amr(\\d+)_thr([0-9p]+)\\.csv$")

    items = []
    for p in sorted(results_dir.glob(f"b0_{shape_tag}_amr*_thr*.csv")):
        m = pat.match(p.name)
        if not m:
            continue
        amr = int(m.group(1))
        thr = float(m.group(2).replace("p", "."))
        rows = read_csv(p)
        d0 = [int(r["d0"]) for r in rows]
        home = [to_float(r["mean_absdiff_home"]) for r in rows]
        hyb = [to_float(r["mean_absdiff_hybrid"]) for r in rows]
        items.append((amr, thr, d0, home, hyb, p.name))

    if not items:
        raise RuntimeError(f"No CSVs found for shape '{shape_tag}' in {results_dir}")

    # Plot HOME vs Legacy error curves (these will be flat-ish across d0, but differ per AMR run).
    plt.figure()
    for amr, thr, d0, home, hyb, name in sorted(items, key=lambda t: (t[1], t[0])):
        plt.plot(d0, home, marker="o", label=f"HOME (amr={amr}, thr={thr})")
    plt.yscale("log")
    plt.xlabel("d0")
    plt.ylabel("Mean abs diff of near-wall |u| vs Legacy")
    plt.title(f"{shape_tag}: HOME vs Legacy (wall AMR sweep)")
    plt.grid(True, which="both", linestyle="--", linewidth=0.5)
    plt.legend(fontsize=8)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=180)
    print("Saved:", out_path)

    # Plot HYBRID(B0) vs Legacy error curves.
    out2 = out_path.with_name(out_path.stem + "_hybrid.png")
    plt.figure()
    for amr, thr, d0, home, hyb, name in sorted(items, key=lambda t: (t[1], t[0])):
        plt.plot(d0, hyb, marker="o", label=f"Hybrid(B0) (amr={amr}, thr={thr})")
    plt.yscale("log")
    plt.xlabel("d0")
    plt.ylabel("Mean abs diff of near-wall |u| vs Legacy")
    plt.title(f"{shape_tag}: Hybrid(B0) vs Legacy (wall AMR sweep)")
    plt.grid(True, which="both", linestyle="--", linewidth=0.5)
    plt.legend(fontsize=8)
    plt.savefig(out2, dpi=180)
    print("Saved:", out2)


if __name__ == "__main__":
    main()
